### ISSUE TITLE
Accessing Keys in translation file

### ISSUE THREAD

**Issue by GozuPro** [microapps/gatsby-plugin-react-i18next#36]
Is nesting supported in translation files? 
https://www.i18next.com/translation-function/essentials

```
{
    "key": "value of key",
    "look": {
        "deep": "value of look deep"
    }
}

<h1>{t('look.deep')}</h1> // the following doesn't work for me
```
In the example, everything is at the top level.

**Comment by ManuelFeller** [comment]
I also have this issue, and I am trying to find out why it does not work. When going with the above example and calling `{t('look')}` I get the output `key 'look (en)' returned an object instead of string.`...
When I go by `{t('look.deep')}` the output is just `look.deep`.

Does anyone have an idea why it behaves like that and not like the original useTranslation()? I'm still trying to understand the code...

**Comment by ManuelFeller** [comment]
OK, I think solved this issue.
It's due to the configuration example given in the readme (see your `gatsby-config-js`):
```
  ...
   i18nextOptions: {
    interpolation: {
      escapeValue: false
    },
    keySeparator: false, // <-- this one "disables" the nesting, just remove this line and it should work (it did for me)
    nsSeparator: false
  },
  ...
```
At https://www.i18next.com/overview/configuration-options#misc you find the explanation about this configuration option / parameter. Hope this helps you @GozuPro - and all others that may have an issue with this in the future ;-)

**Comment by jimmyn** [comment]
As I mentioned in the example it is a set of options I'm using to allow message content as a key. So you can have a code like

```jsx
<Trans>Whatewer is your message</Trans>
```

Without specifying any key. But this is totally optional. 

Closing this issue.
