### ISSUE TITLE
No rebuild when locales are changed

### ISSUE THREAD

**Issue by screendriver** [microapps/gatsby-plugin-react-i18next#4]
It would be great when the site gets rebuild / refreshed (HMR) when I change something in my locales files like it does when I change something in my React components. At the moment I have to restart the development server all the time.

**Comment by jimmyn** [comment]
@screendriver not sure this is possible, but I'm using a different approach. All my translations are in code and then automatically extracted to json files. You can check how it's done [here](https://github.com/microapps/gatsby-plugin-react-i18next#how-to-extract-translations-from-pages_)

**Comment by screendriver** [comment]
Thanks for the tip. But I use TypeScript without any Babel stuff 😉

**Comment by jimmyn** [comment]
Extracting transaction strings to JSON is not related to your build process

**Comment by jimmyn** [comment]
This is not something that can be done easily, closing for now. PR's are welcome.

**Comment by jngbng** [comment]
In my case, even restarting dev server does not update contents. The content updates only after running `gastby clean`.

**Comment by screendriver** [comment]
Same here. At least sometimes 🤔

**Comment by jngbng** [comment]
is there any way to force rebuild json except `gastby clean`? regenerating all image thumbnails are painful..

**Comment by jngbng** [comment]
I deleted namespace-related code and put back all key-values to `translation.json` as introduced in `README.md` and hot reload started working again. 🤔

**Comment by jdtzmn** [comment]
I'm going to take a stab at fixing this.

**Comment by jngbng** [comment]
@jdtzmn  Good news! I made a hot-fix for this issue by loading json files using graphql again.
https://github.com/jngbng/gatsby-plugin-react-i18next

**Comment by jdtzmn** [comment]
@jngbng Incredible! I started doing it the exact same way 😂! Did you open a pull request for it? I didn’t see one when I looked.

**Comment by Tstassin** [comment]
Same problem using gatsby, I have to do `gatsby clean && gatsby develop` + force hard refresh in the browser each time I modify locales files..

**Comment by jngbng** [comment]
@jdtzmn  Not yet. I made this patch a few days ago as well after bearing a couple of months. :)

I wonder @jimmyn would like this patch since my patch (https://github.com/jngbng/gatsby-plugin-react-i18next/commit/b44f6aea8f62e86a73bde7bc6af7e73972c1a0bd) is against the motivation of this plugin.

> This plugin does not require fetching translations with graphql query on each page, everything is done automatically. Just use react-i18next to translate your pages.

To meet this motivation, we might have to implement something like `gatsby-source-filesystem` within this plugin, which would be against the architecture of gatsby plugin system. (https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/naming-a-plugin/)

And I deleted `path` option in my patch since as this option does not work well and causes confusion for now. (If I made PR, this should be restored for backward compatibility, though.)

Anyway, if @jimmyn like it, I would make a pull request.

**Comment by jdtzmn** [comment]
@jngbng I think we should still open a PR regardless of whether @jimmyn responds. I will often look at the open pull requests of a package that is not "widely-used," and had I seen a "fix for no rebuilds when locales are changed," I would have just used that version directly.

In other words, I think it will be helpful for others who find this repo in the future. Plus, the more others see the pull request and can voice their support for it, the more feedback we'll get, and the faster it will get merged.

**Comment by zgababa** [comment]
It seems that when you modify a variable in gatsby-plugin-react-i18next from `gatsby-config.js` file, like `debug: false` to `debug: true`. 

At next `npm run dev`, your translations files will be updated. It's not perfect, but faster that `gatsby clean`

Hope that your PR will be accepted @jngbng !

**Comment by Tstassin** [comment]
> In other words, I think it will be helpful for others who find this repo in the future. Plus, the more others see the pull request and can voice their support for it, the more feedback we'll get, and the faster it will get merged.

Agreed, having to maintain a fork for such a feature will be hard and prone to breaking changes.
Isn't sourcing files into graphql the "gastby way" of interacting with content ?
I hope this feature could be merged, and the plugin allow a two way usage : sourcing from the files directly, or using nodes.
I understand that in some projects i18n locales are managed in another scope and HMR/hot reload is not mandatory, but in other projects where text is continuously drafted/changed with layout it's a real pain and a real need.

**Comment by jimmyn** [comment]
Guys I'm sorry, I don't have much time right now to review everything but I'll try to check this PR in upcoming days

**Comment by jdtzmn** [comment]
Thank you @jimmyn! @jngbng will you work on a PR? I'm somewhat available, so let me know if I can assist in any way. I'm excited to get this merged.

**Comment by jngbng** [comment]
| Isn't sourcing files into graphql the "gastby way" of interacting with content ?

@Tstassin It is the "gastby way". What I wanted to say was that Gatsby recommends that load resources using preexisting source plugins, instead of implementing it again in our plugin.

@jimmyn  @jdtzmn  I've just opened PR. https://github.com/microapps/gatsby-plugin-react-i18next/pull/43
