### ISSUE TITLE
fallbackLng does not work as expected

### ISSUE THREAD

**Issue by screendriver** [microapps/gatsby-plugin-react-i18next#6]
When I set `fallbackLng` (or in in this plugin called `defaultLanguage`) it does not work 100% as described in the official docs of the [resolution order](https://www.i18next.com/principles/translation-resolution#resolution-order): `"If a key is not found, i18next then walks through the list of languages, which consists of the current language(s) and the fallback language(s)."`

When I init `i18next` in a small demo app like this

```ts
i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: 'en',
    resources: {
      en: {
        translation: {
          foo: 'en-bar',
        },
      },
      de: {
        translation: {
          // foo: 'de-bar', <-- commented out so the key can not be found!
        },
      },
    },
    keySeparator: false,
    interpolation: {
      escapeValue: false,
    },
  });
```

and I do a `<div>{t('foo')}</div>` in a Browser where the language is set to German (_de_) then i18next finds the key `foo` in `en` because of the resolution order and the app shows `en-bar`.

When I do the same with Gatsby and this plugin

```js
{
  resolve: 'gatsby-plugin-react-i18next',
  options: {
    path: `${__dirname}/src/locales`,
    languages: ['en', 'de'],
    defaultLanguage: 'en',
    redirect: true,
    i18nextOptions: {
      interpolation: {
        escapeValue: false,
      },
    },
  },
},
```

it displays, as a last resort, only the raw key `foo` instead of `en-bar`.

**Comment by jimmyn** [comment]
This plugin is not designed to work with the fallback language. Because translations are done on build time it fetches only the page language. You can either use default values in your translations like `t('key', 'default value to show')` or use the entire message as a key as [described here](https://www.i18next.com/principles/fallback#key-fallback). In this case your key will be a fallback message itself.
